# Generated by Django 4.2.20 on 2025-04-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_preregistration_member_pre_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
