# Generated by Django 4.2.20 on 2025-04-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_preregistration_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='progress',
            field=models.IntegerField(default=0, help_text='Overall progress percentage'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='duration_weeks',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='target_goal',
            field=models.CharField(default='General Fitness', max_length=50),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='title',
            field=models.CharField(default='Untitled Plan', max_length=100),
        ),
    ]
