# Generated by Django 4.2.20 on 2025-04-06 17:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_weightentry_progressnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='trainer',
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='duration_weeks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='myapp.member'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='target_goal',
            field=models.CharField(choices=[('muscle_gain', 'Muscle Gain'), ('weight_loss', 'Weight Loss'), ('endurance', 'Endurance'), ('strength', 'Strength'), ('flexibility', 'Flexibility')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
