# Generated by Django 4.2.20 on 2025-04-06 19:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_workoutplan_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='description',
            field=models.TextField(default='Default workout description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='schedule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='trainer',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='myapp.trainer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.trainer'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='duration_weeks',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.member'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='target_goal',
            field=models.CharField(default='General Fitness', max_length=50),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='title',
            field=models.CharField(default='Untitled Plan', max_length=100),
        ),
    ]
